-- 秒杀执行存储过程
-- ；
DELIMITER $$ -- console ;转换为 $$
-- 定义存储过程
-- 参数：in  输入参数；out 输出参数
-- CREATE PROCEDURE `seckill`.`execute_seckill`
-- 存储过程
-- 1、存储过程优化：事务行级锁持有的时间
-- 2、不要过度依赖存储过程
-- 3、简单的逻辑可以应用存储过程
-- 4、QPS：一个秒杀单6000/qps